"""Reference projects, from the Codutti "Best References" deck.

Each entry: slug, title, location, country, year ("" until confirmed),
sector, preview (one line for the card), about (the project), scope (what
Codutti supplied), pages (deck pages the photos come from; a page given as
(n, "left"/"right") keeps only the images on that half).
Years are not stated in the deck: fill them in here when known.
"""

PROJECTS = [
    dict(slug="sberbank", title="Sberbank", location="Russia", year="", sector="Banking",
         preview="An executive office for one of Russia's leading banks.",
         about="A director's office designed as a working room and a place to receive guests: a classical interior with panelled walls, parquet and tall windows, furnished in warm wood and ivory leather.",
         scope=["Executive desk with wooden base and modesty panel", "Meeting extension joined to the desk", "Ivory leather executive and visitor chairs", "Lounge armchairs and storage units"],
         pages=[2]),
    dict(slug="security-national-pr", title="Security National Pr", location="Saudi Arabia", year="", sector="Government",
         preview="A council chamber built around one continuous wood-veneer table.",
         about="A large council chamber for official sessions. A single ring of tables in wood veneer seats every delegate, with microphones and cable management built into the top.",
         scope=["Ring-shaped council table in wood veneer, made to measure", "Integrated microphones and cable management", "Leather conference chairs for every seat"],
         pages=[3]),
    dict(slug="ministry-of-finance", title="Ministry of Finance", location="Saudi Arabia", year="", sector="Government",
         preview="Council room, meeting rooms and offices for a government ministry.",
         about="A complete fit-out across several floors: a representative council room with a curved table set under a circular ceiling, meeting rooms for internal teams and glass-partitioned offices.",
         scope=["Curved council table with leather-covered fronts", "Meeting tables for boardrooms and team rooms", "Executive desks and glass-top desks", "Executive and conference seating"],
         pages=[4, 5]),
    dict(slug="ministry-of-investment", title="Ministry of Investment", location="Saudi Arabia", year="", sector="Government",
         preview="A boardroom, executive suites and meeting rooms for the Ministry.",
         about="A long-running relationship covering the Ministry's representative spaces: a boardroom with a table for more than twenty people, executive offices with private meeting areas, and meeting rooms finished in walnut and light leather.",
         scope=["Boardroom table for 20+ seats with integrated technology", "Executive desks with side units and credenzas", "Meeting tables and coffee tables", "Reception desk", "Executive, visitor and conference chairs"],
         pages=[6, 37, 38, 39, 40]),
    dict(slug="bank-al-bilad", title="Bank Albilad", location="Saudi Arabia", year="", sector="Banking",
         preview="Customer service desks and consultation areas for bank branches.",
         about="Branch interiors where customers are received at open service desks. White curved counters, side tables and lounge seating keep the space light and easy to read.",
         scope=["Curved customer service desks in white", "Consultation tables", "Visitor and lounge seating"],
         pages=[7]),
    dict(slug="torre-mohamed", title="Torre Mohamed", location="Morocco", year="", sector="Government",
         preview="An assembly hall with a curved council table and built-in screens.",
         about="A representative tower building with an assembly hall at its heart: a curved council table under a timber ceiling, with retractable screens at every seat. Meeting rooms and the reception complete the project.",
         scope=["Curved council table with retractable screens", "Meeting room tables", "Reception desk with the client's logo", "Conference seating"],
         pages=[8, 9]),
    dict(slug="rossetto-trade", title="Rossetto Trade", location="Italy", year="", sector="Corporate",
         preview="Headquarters with auditorium, boardroom and training rooms.",
         about="A corporate headquarters where the company meets its staff and partners: an auditorium under a timber roof, an oval boardroom and training rooms.",
         scope=["Auditorium seating", "Oval boardroom table with integrated technology", "Conference chairs", "Meeting and training room furniture"],
         pages=[10]),
    dict(slug="rtcc-dubai", title="RTCC", location="Dubai, UAE", year="", sector="Government",
         preview="An oval conference room with a screen at every seat.",
         about="A command and conference room organised around an oval table. Every seat has a retractable monitor and connections built into the top.",
         scope=["Oval conference table with retractable monitors", "Integrated connections and cable management", "Conference chairs"],
         pages=[11]),
    dict(slug="moscow-executive-offices", title="Executive Offices", location="Moscow, Russia", year="", sector="Corporate",
         preview="Classic executive offices in warm wood and black leather.",
         about="Executive offices in a classical building, with chandeliers, curtains and parquet. Wood-veneer furniture and black leather seating keep the tone formal and warm.",
         scope=["Executive desks with meeting extensions", "Oval meeting tables", "Black leather executive and visitor chairs"],
         pages=[12]),
    dict(slug="private-office", title="Private Office", location="", year="", sector="Private",
         preview="A private office with an executive desk and a meeting table.",
         about="A private office with a corner meeting area. Dark finishes and leather chairs against light walls and large windows.",
         scope=["Executive desk with side return", "Meeting table", "Leather chairs and lounge seating"],
         pages=[13]),
    dict(slug="phi-group", title="phi Group", location="Saudi Arabia", year="", sector="Corporate",
         preview="Headquarters with operative workstations and executive offices.",
         about="Offices for a company group: open-plan operative areas, glass-partitioned offices and executive rooms, all in one consistent palette.",
         scope=["Operative desks and workstations", "Executive desks with storage", "Meeting tables", "Task, executive and visitor chairs"],
         pages=[14, 15]),
    dict(slug="saudi-investment-bank", title="Saudi Investment Bank", location="Saudi Arabia", year="", sector="Banking",
         preview="Branch counters in stone, waiting areas and private offices.",
         about="A bank branch with stone-finished service counters, a waiting area and private offices for relationship managers, behind the bank's yellow frontage.",
         scope=["Stone-finished service counters", "Waiting area seating", "Executive desks for private offices"],
         pages=[16, 17]),
    dict(slug="shanghai", title="Executive Offices", location="Shanghai, China", year="", sector="Corporate",
         preview="Executive offices and lounges with white desks and black leather.",
         about="Executive offices with views over the city: white desks, black leather chairs and lounge corners for informal meetings.",
         scope=["Executive desks in white", "Storage walls", "Executive and visitor chairs", "Lounge seating"],
         pages=[18]),
    dict(slug="sanremo", title="Glasshouse Meeting Space", location="Sanremo, Italy", year="", sector="Hospitality",
         preview="A meeting space inside a glasshouse full of plants.",
         about="A glasshouse among the plants, set up for meetings and work: a round table with high stools and small tables around it.",
         scope=["Round meeting table", "High stools", "Small tables"],
         pages=[19]),
    dict(slug="dubai-open-office", title="Open Office", location="Dubai, UAE", year="", sector="Corporate",
         preview="Open-plan operative workstations with integrated storage.",
         about="An open-plan office under an exposed ceiling: rows of operative workstations with storage units that double as dividers.",
         scope=["Operative workstations", "Storage units used as dividers", "Task chairs"],
         pages=[20]),
    dict(slug="moscow-offices", title="Offices", location="Moscow, Russia", year="", sector="Corporate",
         preview="Contemporary offices with meeting rooms and an executive suite.",
         about="Contemporary offices with linear lighting and wood floors: meeting rooms, team areas and an executive office.",
         scope=["Executive desk", "Meeting tables", "Operative desks", "Executive and visitor chairs"],
         pages=[21]),
    dict(slug="loreal-paris", title="L'Oréal", location="Paris, France", year="", sector="Corporate",
         preview="Glass-partitioned offices with light, glass-top desks.",
         about="Offices behind glass partitions, kept as light as possible: glass-top desks and white executive chairs.",
         scope=["Glass-top desks", "Executive chairs", "Meeting tables"],
         pages=[22]),
    dict(slug="al-rajhi-bank", title="Al Rajhi Bank", location="Saudi Arabia", year="", sector="Banking",
         preview="Headquarters floors with benches, meeting pods and executive offices.",
         about="Several floors of a banking headquarters: long workstation benches with planters, meeting pods in strong colours, glass-top executive desks and team tables.",
         scope=["Workstation benches with planters", "Meeting tables for pods and team rooms", "Glass-top executive desks", "Task, executive and meeting chairs"],
         pages=[23, 24, 25, 26]),
    dict(slug="light-building", title="Light + Building", location="Frankfurt, Germany", year="", sector="Trade fair",
         preview="Codutti's meeting area at the Light + Building fair.",
         about="A meeting area for the Light + Building fair: a dark meeting table and wooden shell chairs against a jungle wallpaper.",
         scope=["Meeting table", "Wood shell chairs", "Stand furniture"],
         pages=[27]),
    dict(slug="orgatec", title="Orgatec", location="Cologne, Germany", year="", sector="Trade fair",
         preview="The Codutti stand at Orgatec, Cologne.",
         about="Codutti's stand at Orgatec: an executive office set, a round meeting table and shelving units, among patterned acoustic walls.",
         scope=["Executive desk", "Round meeting table", "Shelving and storage", "Seating"],
         pages=[(28, "left"), 30]),
    dict(slug="workspace-dubai", title="Workspace", location="Dubai, UAE", year="", sector="Trade fair",
         preview="The Codutti stand at the Workspace fair, Dubai.",
         about="Codutti's stand at Workspace Dubai, built around a sharing table on a blue frame with high stools.",
         scope=["Sharing table", "Stools", "Shelving"],
         pages=[(28, "right")]),
    dict(slug="remal-project", title="Remal Project", location="Saudi Arabia", year="", sector="Corporate",
         preview="Hundreds of workstations across open-plan floors.",
         about="Large open-plan floors furnished with workstations divided by blue screens, repeated across the whole building.",
         scope=["Operative workstations", "Blue privacy screens", "Task chairs"],
         pages=[29]),
    dict(slug="interlux", title="Interlux", location="Morocco", year="", sector="Corporate",
         preview="A round meeting table with an open centre.",
         about="A meeting room built around a round table with an open centre, fitted with connections at every seat.",
         scope=["Round meeting table with open centre", "Integrated connections", "Leather executive chairs"],
         pages=[31]),
    dict(slug="trosselli", title="Trosselli", location="Switzerland", year="", sector="Corporate",
         preview="An executive office and a round meeting table on blue carpet.",
         about="An executive office with a white-topped desk on a dark frame with drawers, and a round meeting table, set on deep blue carpet.",
         scope=["Executive desk with drawers", "Round meeting table", "Executive and visitor chairs", "Lounge seating"],
         pages=[32]),
    dict(slug="ferrbatt", title="Ferrbatt", location="Italy", year="", sector="Corporate",
         preview="Executive offices and meeting rooms for an Italian company.",
         about="Offices for an Italian company: executive rooms with curved wood desks and matching credenzas, a meeting room and glass-top desks.",
         scope=["Executive desks with curved wood bases", "Credenzas", "Meeting table", "Glass-top desks", "Executive and visitor chairs"],
         pages=[33, 34, 35, 36]),
]
